"""add api key and admin audit log tables

Revision ID: 12aba248c961
Revises: 2e33de3888f6
Create Date: 2026-06-08 15:12:45.857244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '12aba248c961'
down_revision: Union[str, Sequence[str], None] = '2e33de3888f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminauditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entityType', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entityId', sa.Integer(), nullable=False),
    sa.Column('payloadSnapshot', sa.Text(), nullable=True),
    sa.Column('ipAddress', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adminauditlog_userId'), 'adminauditlog', ['userId'], unique=False)
    op.create_table('apikey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keyHash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keyPrefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('lastUsedAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikey_keyHash'), 'apikey', ['keyHash'], unique=False)
    op.create_index(op.f('ix_apikey_userId'), 'apikey', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apikey_userId'), table_name='apikey')
    op.drop_index(op.f('ix_apikey_keyHash'), table_name='apikey')
    op.drop_table('apikey')
    op.drop_index(op.f('ix_adminauditlog_userId'), table_name='adminauditlog')
    op.drop_table('adminauditlog')
    # ### end Alembic commands ###
