"""add reading line columns to history

Revision ID: 2e33de3888f6
Revises: 1e3b78a2ff70
Create Date: 2026-06-08 00:07:48.836662

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e33de3888f6'
down_revision: str | Sequence[str] | None = '1e3b78a2ff70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('lastReadBlockIndex', sa.Integer(), nullable=True))
    op.add_column('history', sa.Column('blockOffsetPercent', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'blockOffsetPercent')
    op.drop_column('history', 'lastReadBlockIndex')
    # ### end Alembic commands ###
