"""add_features_search_comments_reviews_notifications_progress_reset_trending

Revision ID: 5eb90ae43e02
Revises: fc800da5045b
Create Date: 2026-05-31 12:12:07.421524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5eb90ae43e02'
down_revision: Union[str, Sequence[str], None] = 'fc800da5045b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('novelId', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novelId'], ['novel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'novelId')
    )
    op.create_index(op.f('ix_review_novelId'), 'review', ['novelId'], unique=False)
    op.create_index(op.f('ix_review_userId'), 'review', ['userId'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('novelId', sa.Integer(), nullable=True),
    sa.Column('chapterId', sa.Integer(), nullable=True),
    sa.Column('isRead', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapterId'], ['chapter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['novelId'], ['novel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_chapterId'), 'notification', ['chapterId'], unique=False)
    op.create_index(op.f('ix_notification_novelId'), 'notification', ['novelId'], unique=False)
    op.create_index(op.f('ix_notification_userId'), 'notification', ['userId'], unique=False)
    op.add_column('comment', sa.Column('parentId', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('depth', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_comment_parentId'), 'comment', ['parentId'], unique=False)
    # SQLite does not support ALTER TABLE ADD CONSTRAINT; FK enforced at app level for SQLite
    conn = op.get_bind()
    if conn.dialect.name != 'sqlite':
        op.create_foreign_key(None, 'comment', 'comment', ['parentId'], ['id'], ondelete='CASCADE')
    op.add_column('history', sa.Column('scrollPosition', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('progressPercent', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('novel', sa.Column('viewCount', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('resetTokenHash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('resetTokenExpires', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_resetTokenHash'), 'user', ['resetTokenHash'], unique=False)

    # Add full-text search vector for PostgreSQL
    conn = op.get_bind()
    if conn.dialect.name == 'postgresql':
        op.execute(sa.text("""
            ALTER TABLE novel ADD COLUMN search_vector tsvector
            GENERATED ALWAYS AS (
                to_tsvector('english', coalesce(title, '') || ' ' || coalesce(author, '') || ' ' || coalesce(synopsis, ''))
            ) STORED;
        """))
        op.execute(sa.text("CREATE INDEX idx_novel_search ON novel USING gin(search_vector);"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    if conn.dialect.name == 'postgresql':
        op.execute(sa.text("DROP INDEX IF EXISTS idx_novel_search;"))
        op.execute(sa.text("ALTER TABLE novel DROP COLUMN IF EXISTS search_vector;"))

    op.drop_index(op.f('ix_user_resetTokenHash'), table_name='user')
    op.drop_column('user', 'resetTokenExpires')
    op.drop_column('user', 'resetTokenHash')
    op.drop_column('novel', 'viewCount')
    op.drop_column('history', 'progressPercent')
    op.drop_column('history', 'scrollPosition')
    conn = op.get_bind()
    if conn.dialect.name != 'sqlite':
        op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_parentId'), table_name='comment')
    op.drop_column('comment', 'depth')
    op.drop_column('comment', 'parentId')
    op.drop_index(op.f('ix_notification_userId'), table_name='notification')
    op.drop_index(op.f('ix_notification_novelId'), table_name='notification')
    op.drop_index(op.f('ix_notification_chapterId'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_review_userId'), table_name='review')
    op.drop_index(op.f('ix_review_novelId'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
