"""Initial migration

Revision ID: fc800da5045b
Revises: 
Create Date: 2026-05-25 13:53:42.757149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc800da5045b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=True)
    op.create_table('novel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('originalTitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('romajiTitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('coverUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('synopsis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('averageRating', sa.Float(), nullable=False),
    sa.Column('ratingCount', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novel_slug'), 'novel', ['slug'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novelId', sa.Integer(), nullable=False),
    sa.Column('chapterNum', sa.Integer(), nullable=False),
    sa.Column('rawTitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rawContent', sa.Text(), nullable=True),
    sa.Column('sourceUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['novelId'], ['novel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novelId', 'chapterNum')
    )
    op.create_index(op.f('ix_chapter_novelId'), 'chapter', ['novelId'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('novelId', sa.Integer(), nullable=False),
    sa.Column('chapterNum', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novelId'], ['novel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'novelId')
    )
    op.create_index(op.f('ix_history_novelId'), 'history', ['novelId'], unique=False)
    op.create_index(op.f('ix_history_userId'), 'history', ['userId'], unique=False)
    op.create_table('library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('novelId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novelId'], ['novel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'novelId')
    )
    op.create_index(op.f('ix_library_novelId'), 'library', ['novelId'], unique=False)
    op.create_index(op.f('ix_library_userId'), 'library', ['userId'], unique=False)
    op.create_table('novelgenrelink',
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('novel_id', 'genre_id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('novelId', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novelId'], ['novel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'novelId')
    )
    op.create_index(op.f('ix_rating_novelId'), 'rating', ['novelId'], unique=False)
    op.create_index(op.f('ix_rating_userId'), 'rating', ['userId'], unique=False)
    op.create_table('chaptertranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapterId', sa.Integer(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('publishedAt', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapterId'], ['chapter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapterId', 'language')
    )
    op.create_index(op.f('ix_chaptertranslation_chapterId'), 'chaptertranslation', ['chapterId'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('novelId', sa.Integer(), nullable=True),
    sa.Column('chapterId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapterId'], ['chapter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['novelId'], ['novel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_chapterId'), 'comment', ['chapterId'], unique=False)
    op.create_index(op.f('ix_comment_novelId'), 'comment', ['novelId'], unique=False)
    op.create_index(op.f('ix_comment_userId'), 'comment', ['userId'], unique=False)
    op.create_table('unlockedchapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('translationId', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('unlockedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['translationId'], ['chaptertranslation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'translationId')
    )
    op.create_index(op.f('ix_unlockedchapter_translationId'), 'unlockedchapter', ['translationId'], unique=False)
    op.create_index(op.f('ix_unlockedchapter_userId'), 'unlockedchapter', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unlockedchapter_userId'), table_name='unlockedchapter')
    op.drop_index(op.f('ix_unlockedchapter_translationId'), table_name='unlockedchapter')
    op.drop_table('unlockedchapter')
    op.drop_index(op.f('ix_comment_userId'), table_name='comment')
    op.drop_index(op.f('ix_comment_novelId'), table_name='comment')
    op.drop_index(op.f('ix_comment_chapterId'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_chaptertranslation_chapterId'), table_name='chaptertranslation')
    op.drop_table('chaptertranslation')
    op.drop_index(op.f('ix_rating_userId'), table_name='rating')
    op.drop_index(op.f('ix_rating_novelId'), table_name='rating')
    op.drop_table('rating')
    op.drop_table('novelgenrelink')
    op.drop_index(op.f('ix_library_userId'), table_name='library')
    op.drop_index(op.f('ix_library_novelId'), table_name='library')
    op.drop_table('library')
    op.drop_index(op.f('ix_history_userId'), table_name='history')
    op.drop_index(op.f('ix_history_novelId'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_chapter_novelId'), table_name='chapter')
    op.drop_table('chapter')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_novel_slug'), table_name='novel')
    op.drop_table('novel')
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.drop_table('genre')
    # ### end Alembic commands ###
